### ISSUE TITLE
Logo Proposal as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [keithrbennett/trick_bag#3]
Hello again, Sir. Do you mind if I contribute to designing any logos for this project?

**Comment by keithrbennett** [comment]
That would be great, thank you!

**Comment by anharismail** [comment]
Hello Sir @keithrbennett , this is my idea for your logo project. Please just tell if there is any revisions or opinion to my proposal.

![trickbag ver 1](https://user-images.githubusercontent.com/37614260/46912230-07593480-cf9a-11e8-8550-34a4c3613cee.png)

**Comment by anharismail** [comment]
Hello Sir @keithrbennett , Thanks for your comments and inputs.
I've modified my logo. How about this version?

![trickbag ver 2](https://user-images.githubusercontent.com/37614260/46938154-37cdcb00-d08d-11e8-86df-2e6c1395c0ce.png)

**Comment by keithrbennett** [comment]
Thanks, Anhar. Sorry, but it still looks like a tea kettle to me.

I like the idea of the wand and the stars, but the wand looks like a spout
to me and the stars are like steam.

Could we try removing the stripe and circles from the bag, and putting the
wand and stars on the bag as part of the bag design?

Thanks.

**Comment by anharismail** [comment]
Hello Sir @keithrbennett , Thanks for your suggestions.

I've tried do as your suggestions. Please just tell me your thoughts about this.

![trickbag ver 3](https://user-images.githubusercontent.com/37614260/47780637-5b9c3c80-dd2e-11e8-8f7c-659cc5efaa51.png)

**Comment by keithrbennett** [comment]
Hi, Anhar. Thanks for making those changes. I like it but have a couple of suggestions.

Could you make the wand narrower? For reference, here are some wand designs that I like:

* https://www.istockphoto.com/vector/magic-wand-with-blue-sta-and-sparkle-trail-gm940159754-257025843
* http://m.sweetclipart.com/magic-wand-silhouette-clip-art-2/

Also, could I see what it would look like with the entire logo in the same color (green)? I find the black a little harsh.

Thanks for your patience.

**Comment by anharismail** [comment]
Hello Sir @keithrbennett , very happy because you always give your responses. What I'm doing now is about to improve my design skill, so please just tell me anything about my logo design because it was good for me.

Anyway, here my revisions followed your guide before. There are two versions. Please give your feedback again :)

### First,
![trickbag ver 4](https://user-images.githubusercontent.com/37614260/47905099-d85b2200-deb8-11e8-9624-c5443b1abd9c.png)

### Second,
![trickbag ver 5](https://user-images.githubusercontent.com/37614260/47905118-e14bf380-deb8-11e8-880c-fe42385bb443.png)

**Comment by keithrbennett** [comment]
Thanks, @anharismail, I like the way this looks! One more suggestion, if I may...

I'd like if we can change the shape of the bag to look less like a woman's pocketbook and more like a doctor's bag. I think that means less like a trapezoid and more like a rectangle. Here are some samples (for the shape but not necessarily the detail):

https://cenzobags.com/product/cenzo-leather-doctor-bag/
https://www.pinterest.com/pin/79235274667004932/
https://www.pinterest.com/pin/698550592178746801/

Thanks again!

**Comment by keithrbennett** [comment]
Sorry, I forgot to mention, I like design #1 better than #2.

**Comment by anharismail** [comment]
Hi Sir @keithrbennett , thanks a lot for many inputs and suggestions for the design. Here my ideas trying to follow your suggestions. Please give your feedbacks and opinions again.

![trickbag ver 6](https://user-images.githubusercontent.com/37614260/48297248-82006b80-e4d6-11e8-88d8-529a938e87e0.png)

**Comment by keithrbennett** [comment]
@anharismail I like it! Thank you very much!

**Comment by keithrbennett** [comment]
@anharismail Would you be able to make a pull request with these files? If you could follow the example at https://github.com/keithrbennett/wifiwand/tree/master/logo that would be ideal; but if you just put the files in a `logo` directory I could take care of the .md file.

**Comment by anharismail** [comment]
Thanks for your response, Sir. I'll make a pull request with the following format
